# SPDX-License-Identifier: MulanPSL-2.0
"""mapping_rbnx atlas bridge — robonix v0.1 Capability flow.

Responsibilities (kept tight; SLAM nodes do the actual work):
  1. Register `mapping` as a capability with atlas, declare a
     `service/map/driver` interface.
  2. Wait for `Driver(CMD_INIT, config_json)` from rbnx — config arrives
     ONLY through this gRPC channel (NEVER from disk / env). The cfg
     dict carries:
       - algo:    rtabmap | dlio | fastlio2[broken]
       - sensors: lidar2d / lidar3d / rgb / depth / imu / odom booleans
       - platform: x86_desktop / jetson_orin
  3. Resolve sensor primitives via atlas, write `/tmp/<algo>_resolved.yaml`
     for the launch file (start_engine.sh greps these out).
  4. Declare the algo-appropriate output endpoints on atlas, ALL under
     the SAME contract surface (robonix/service/map/*) so consumers
     (scene, nav) are algo-agnostic.

slam_toolbox + cartographer were removed in favour of rtabmap after
extensive head-to-head testing in webots: rtabmap handles curve-motion
mapping, loop closure, and depth fusion better than either alternative
for the cost of one extra dependency.
"""
from __future__ import annotations

import json
import logging
import os
import sys
import time
from pathlib import Path
from typing import Optional

logging.basicConfig(level=logging.INFO,
                    format="[atlas_bridge] %(levelname)s %(message)s")
log = logging.getLogger("mapping_rbnx.atlas_bridge")


# ── Generated proto stubs ─────────────────────────────────────────────────────
# Codegen drops them under <pkg>/rbnx-build/codegen/proto_gen/. PYTHONPATH
# is set by docker entrypoint.sh.
import grpc  # noqa: E402

import atlas_pb2 as pb  # type: ignore
import atlas_pb2_grpc as pb_grpc  # type: ignore

from robonix_api import Service, Ok, Err, Deferred, ATLAS  # noqa: E402

# Map-management gRPC + MCP capabilities (save_map / load_map / pose_estimate).
# Generated by `rbnx codegen` from capabilities/lib/map/srv/*.srv.
import map_pb2  # type: ignore  # noqa: E402
import robonix_contracts_pb2_grpc as contracts_grpc  # type: ignore  # noqa: E402
from map_mcp import (  # type: ignore  # noqa: E402
    SaveMap_Request as McpSaveMapReq,
    SaveMap_Response as McpSaveMapResp,
    ListMaps_Request as McpListMapsReq,
    ListMaps_Response as McpListMapsResp,
    LoadMap_Request as McpLoadMapReq,
    LoadMap_Response as McpLoadMapResp,
    PoseEstimate_Request as McpPoseReq,
    PoseEstimate_Response as McpPoseResp,
    SwitchMode_Request as McpSwitchReq,
    SwitchMode_Response as McpSwitchResp,
    GetMode_Request as McpGetModeReq,
    GetMode_Response as McpGetModeResp,
    DeleteMap_Request as McpDeleteReq,
    DeleteMap_Response as McpDeleteResp,
    ResetMap_Request as McpResetReq,
    ResetMap_Response as McpResetResp,
    GetPose_Request as McpGetPoseReq,
    GetPose_Response as McpGetPoseResp,
)
from mapping_rbnx import map_ops  # noqa: E402
from mapping_rbnx import webui  # noqa: E402
from mapping_rbnx.profiles import resolve_rtabmap_overrides  # noqa: E402


# ── Config ────────────────────────────────────────────────────────────────────
ATLAS_ENDPOINT = os.environ.get("ROBONIX_ATLAS", "127.0.0.1:50051")
CAP_ID = os.environ.get("ROBONIX_CAPABILITY_ID", "mapping")
NAMESPACE = "robonix/service/map"
PKG_HOST_DIR = os.environ.get("ROBONIX_PKG_HOST_DIR", "/mapping")
RESOLVED_DIR = os.environ.get("MAPPING_RESOLVED_DIR", "/tmp")
HEARTBEAT_PERIOD_S = 10.0

# Persistent map store. Each named map lives under {MAPS_DIR}/{map_id}/ and
# survives container restarts ONLY when the deploy bind-mounts a host dir
# here (docker/compose.yaml mounts it; see CAPABILITY.md "persistence").
# Without map_id the package stays ephemeral — exactly the pre-persistence
# behaviour (temp db, wiped each boot).
MAPS_DIR = os.environ.get("MAPPING_MAPS_DIR", "/mapping/maps")
RUNTIME_DB_DIR = os.environ.get("MAPPING_RUNTIME_DB_DIR", "/tmp/robonix-mapping-runtime")


def _truthy(s: str) -> bool:
    return str(s).strip().lower() in ("1", "true", "yes", "on")


# ── Map persistence (map_id / mapping vs localization) ────────────────────────
import re  # noqa: E402

_VALID_MODES = ("mapping", "localization")


def _sanitize_map_id(map_id: str) -> str:
    """Map ids become a directory name, so restrict to a filesystem-safe
    charset. Mirrors scene's ObjectStore sanitiser so a given map_id keys
    the SAME spatial map (mapping) and semantic map (scene) consistently."""
    return re.sub(r"[^A-Za-z0-9._-]", "_", map_id.strip()) or "default"


def _resolve_persistence(cfg: dict) -> dict[str, str]:
    """Resolve a private runtime DB, and only read saved maps in localization.

    ``maps/<map_id>/rtabmap.db`` is an immutable published artifact. RTAB-Map
    must never use it as its active writer database. A mapping session always
    receives a fresh runtime DB; ``save_map`` snapshots that DB atomically into
    a stable map id. Localization first copies the saved artifact to a runtime
    DB, so even RTAB-Map bookkeeping cannot mutate the saved copy.
    """
    raw_id = cfg.get("map_id")
    map_id = _sanitize_map_id(str(raw_id)) if raw_id else ""
    mode = str(cfg.get("map_mode", "mapping")).strip().lower()
    if mode not in _VALID_MODES:
        raise RuntimeError(
            f"map_mode={mode!r} invalid — must be one of {list(_VALID_MODES)}"
        )
    reset = _truthy(cfg.get("reset_map", False))
    if mode == "localization":
        if not map_id:
            raise RuntimeError("map_mode=localization requires a saved map_id")
        map_dir = os.path.join(MAPS_DIR, map_id)
        saved_db = os.path.join(map_dir, "rtabmap.db")
        if not os.path.isfile(saved_db):
            raise RuntimeError(
                f"map_mode=localization but no saved map at {saved_db!r}. "
                "Save a mapping session first, or check MAPPING_MAPS_DIR."
            )
        if reset:
            raise RuntimeError("reset_map=true is meaningless in localization mode")
        runtime_db = map_ops._runtime_db_copy(saved_db, map_id)
        log.info("persistence: localization map_id=%s saved_db=%s runtime_db=%s",
                 map_id, saved_db, runtime_db)
        return {
            "map_id": map_id,
            "map_mode": "localization",
            "database_path": runtime_db,
            "reset_map": "false",
        }

    # Mapping is always a new mutable session. Keep a supplied map_id out of
    # the runtime binding: it identifies a saved artifact, not a live session.
    os.makedirs(RUNTIME_DB_DIR, exist_ok=True)
    runtime_db = os.path.join(
        RUNTIME_DB_DIR,
        f"mapping-{os.getpid()}-{int(time.time() * 1000)}.db",
    )
    log.info("persistence: fresh mapping session runtime_db=%s requested_map_id=%s",
             runtime_db, map_id or "<none>")
    return {
        "map_mode": "mapping",
        "database_path": runtime_db,
        "reset_map": "true",
    }


def _write_rtabmap_overrides(cfg: dict) -> str:
    """Persist deploy-selected RTAB-Map parameter overrides for the launch.

    The bridge is the only sanctioned configuration ingress.  The launcher
    receives a file path instead of a JSON blob so parameter names such as
    ``RGBD/LinearUpdate`` do not need shell escaping.
    """
    profile_name = str(cfg.get("rtabmap_profile") or "").strip()
    raw = cfg.get("rtabmap_params")
    if raw is None and not profile_name:
        return ""
    normalized = resolve_rtabmap_overrides(profile_name, raw)

    path = Path(RESOLVED_DIR) / "rtabmap_overrides.json"
    path.write_text(json.dumps(normalized, sort_keys=True), encoding="utf-8")
    log.info(
        "wrote %d RTAB-Map override(s) profile=%s → %s",
        len(normalized), profile_name or "<none>", path,
    )
    return str(path)


# ── Per-algo output endpoint map ──────────────────────────────────────────────
# Each algo publishes its outputs on different topic names; the bridge
# collapses them onto the SAME contract surface so consumers don't need
# to know which algo is running. Only declare a contract when the algo
# actually publishes it.
# The exported capability surface is FIXED regardless of algo — all
# algos must back the same set of contracts so consumers (scene, nav,
# etc.) only care about contracts, never about which algo is running.
# When an algo can't natively publish a contract, the launch file is
# expected to spawn an adapter node so the topic still exists at the
# bound name. Adding a new contract to this surface is a versioning
# event for the package — bump package.version and update every algo.
_EXPORTED_CONTRACTS: tuple[str, ...] = (
    "robonix/service/map/occupancy_grid",
    "robonix/service/map/pointcloud",
    # SLAM-corrected map-frame pose (loop-closed; can jump on closure).
    # Consumed by scene self-tracker / nav / explore so they don't fall
    # back to raw chassis odom.
    "robonix/service/map/pose",
    # SLAM-corrected continuous odom (frame: odom, smooth between loop
    # closures). For high-rate velocity controllers and trajectory
    # tracking that can't tolerate the jumps in /map/pose.
    "robonix/service/map/odom",
)

# Per-algo: which internal ROS topic backs each exported contract.
# Each entry MUST cover every contract in _EXPORTED_CONTRACTS — that
# invariant is asserted at startup so we fail loud on a misconfigured
# algo rather than silently exporting fewer caps.
_ALGO_TOPIC_BINDINGS: dict[str, dict[str, str]] = {
    "rtabmap": {
        # 2D OccupancyGrid on /map (lidar + depth fusion); 3D fused
        # cloud on /rtabmap/cloud_map (useful for scene's table/chair
        # occlusion layer).
        "robonix/service/map/occupancy_grid": "/map",
        "robonix/service/map/pointcloud":     "/rtabmap/cloud_map",
        # /robonix/map/pose: PoseWithCovarianceStamped published by our
        # tf_to_pose adapter (scripts/tf_to_pose.py, launched alongside
        # rtabmap in rtabmap_2d.launch.py). The adapter polls tf2 for
        # `map → base_link` at 10 Hz and republishes — necessary
        # because rtabmap does NOT publish /localization_pose in
        # mapping mode (only in localization mode after a db is loaded).
        # Earlier this contract was bound to /rtabmap/localization_pose,
        # which silently never produced messages, and consumers
        # (scene's self-tracker) fell back to raw chassis /odom.
        "robonix/service/map/pose":           "/robonix/map/pose",
        # /rtabmap/odom: continuous odometry. When external odom is
        # supplied, rtabmap republishes it under this name with the
        # same map→odom correction baked in via /tf. When icp_odometry
        # is running internally, this IS the odom source.
        "robonix/service/map/odom":           "/rtabmap/odom",
    },
    "dlio": {
        # Direct LiDAR-Inertial Odometry: real-robot 3D livox path.
        # No native 2D OccupancyGrid — projected from /dlio's cloud
        # by a pointcloud_to_grid adapter spawned in the launch.
        "robonix/service/map/occupancy_grid": "/robonix/map/occupancy_grid",
        "robonix/service/map/pointcloud":     "/dlio/odom_node/pointcloud/deskewed",
        # DLIO publishes a single Odometry topic (no separate
        # loop-closed pose stream). We bind both contracts to it; the
        # docstring on /map/pose notes "can jump on closure" but DLIO
        # has no loop closure so it never jumps anyway.
        "robonix/service/map/pose":           "/dlio/odom_node/pose",
        "robonix/service/map/odom":           "/dlio/odom_node/odom",
    },
    "fastlio2": {
        # [BROKEN: drift] same shape as dlio, kept for repro only.
        "robonix/service/map/occupancy_grid": "/robonix/map/occupancy_grid",
        "robonix/service/map/pointcloud":     "/fastlio2/world_cloud",
        "robonix/service/map/pose":           "/fastlio2/lio_odom",
        "robonix/service/map/odom":           "/fastlio2/lio_odom",
    },
}


def _check_binding_complete(algo: str) -> None:
    """Fail loud if an algo doesn't bind every exported contract."""
    bindings = _ALGO_TOPIC_BINDINGS.get(algo, {})
    missing = [c for c in _EXPORTED_CONTRACTS if c not in bindings]
    if missing:
        raise RuntimeError(
            f"algo={algo!r} missing topic binding for contracts: {missing}. "
            f"Every algo must back the full exported surface "
            f"{list(_EXPORTED_CONTRACTS)}; add an adapter node to the "
            f"launch file or update _ALGO_TOPIC_BINDINGS."
        )


# ── Sensor → contract resolution ──────────────────────────────────────────────
# Maps `sensors.*` config flags to the atlas contract IDs scene asks
# atlas to resolve. Each entry: (config_key, contract_id, role_in_lio_yaml).
_SENSOR_CONTRACTS = [
    # (config-key,   contract,                                  yaml-key)
    ("lidar3d",  "robonix/primitive/lidar/lidar3d",       "lidar_topic"),
    ("lidar2d",  "robonix/primitive/lidar/lidar",         "scan_topic"),
    ("imu",      "robonix/primitive/imu/imu",             "imu_topic"),
    ("depth",    "robonix/primitive/camera/depth",        "depth_topic"),
    ("rgb",      "robonix/primitive/camera/rgb",          "rgb_topic"),
    ("odom",     "robonix/primitive/chassis/odom",        "odom_topic"),
]


def _enabled_sensors(cfg: dict) -> dict:
    """Read config.sensors. The deploy manifest is authoritative —
    every robot has different sensors, so we refuse to guess.

    A missing or empty `sensors:` block is a configuration error: the
    operator forgot to declare what the robot has, and silently
    picking "lidar2d + depth" would mask Mid360 deploys (where the
    correct answer is lidar3d + depth) and headless deploys (where the
    correct answer is depth-only). Fail loud instead.
    """
    sensors = cfg.get("sensors")
    if not isinstance(sensors, dict) or not sensors:
        raise RuntimeError(
            "mapping config has no `sensors:` block. Declare which "
            "sensors the robot has, e.g.:\n"
            "  sensors: { lidar2d: true, depth: true, odom: true }     # webots tiago\n"
            "  sensors: { lidar3d: true, depth: true, odom: true, imu: true }  # mid360 robot\n"
            "Supported keys: " + ", ".join(k for k, _, _ in _SENSOR_CONTRACTS)
        )
    out = {}
    for key, _contract, _yaml in _SENSOR_CONTRACTS:
        out[key] = _truthy(sensors.get(key, False))
    if not any(out.values()):
        raise RuntimeError(
            "mapping config has `sensors:` block but every entry is "
            "false/missing — at least one sensor must be enabled."
        )
    return out


# ── Atlas helpers (use Capability's wrapped stub) ────────────────────────────
def _resolve_sensor_endpoint(cap: Service, contract_id: str, provider_id: str = "") -> Optional[str]:
    """ATLAS.find_capability + connect_capability for one ROS2 contract. Returns the topic
    string atlas resolved, or None when no provider is online yet.
    The opened Channel is closed immediately — we just want the
    endpoint string, atlas's bookkeeping for "I'm consuming this"
    is the side benefit."""
    recs = ATLAS.find_capability(
        contract_id=contract_id,
        transport="ros2",
        provider_id=provider_id,
    )
    if not recs:
        if provider_id:
            log.warning("sensor provider %s has no %s on atlas", provider_id, contract_id)
        return None
    rec = recs[0]
    try:
        ch = mapping.connect_capability(rec, contract_id=contract_id, transport="ros2")
    except Exception as e:  # noqa: BLE001
        log.warning("connect %s/%s failed: %s", rec.provider_id, contract_id, e)
        return None
    endpoint = (ch.endpoint or "").strip()
    ch.close()
    return endpoint or None


def _sensor_provider(cfg: dict, sensor_key: str) -> str:
    providers = cfg.get("sensor_providers") or {}
    if not isinstance(providers, dict):
        return ""
    return str(providers.get(sensor_key) or "").strip()


def _resolve_sensors(cap: Service, cfg: dict) -> dict[str, str]:
    """For each enabled sensor, ask atlas for the topic. Empty when
    the primitive isn't online yet (resolved.yaml still useful — the
    launch picks a sane default)."""
    enabled = _enabled_sensors(cfg)
    resolved: dict[str, str] = {}
    for cfg_key, contract_id, yaml_key in _SENSOR_CONTRACTS:
        if not enabled.get(cfg_key):
            continue
        provider_id = _sensor_provider(cfg, cfg_key)
        ep = _resolve_sensor_endpoint(cap, contract_id, provider_id=provider_id)
        if ep:
            resolved[yaml_key] = ep
            if provider_id:
                log.info("resolved %s from %s → %s = %s", contract_id, provider_id, yaml_key, ep)
            else:
                log.info("resolved %s → %s = %s", contract_id, yaml_key, ep)
        else:
            suffix = f" from provider {provider_id}" if provider_id else ""
            log.info("sensor %s (%s%s) not available on atlas yet", cfg_key, contract_id, suffix)
    return resolved


def _retry_resolve(cap: Service, cfg: dict, deadline_s: float = 30.0,
                   settle_s: float = 8.0) -> dict[str, str]:
    """Wait until at least one sensor lands, then absorb late arrivals
    for `settle_s` so all enabled inputs end up in resolved.yaml."""
    deadline = time.time() + deadline_s
    resolved: dict[str, str] = {}
    while time.time() < deadline:
        resolved = _resolve_sensors(cap, cfg)
        if resolved:
            break
        time.sleep(2.0)
    if not resolved:
        log.warning("no sensors discovered within %.1fs — launch will use defaults", deadline_s)
        return {}
    settle_until = time.time() + settle_s
    while time.time() < settle_until:
        time.sleep(2.0)
        more = _resolve_sensors(cap, cfg)
        if len(more) > len(resolved):
            log.info("sensor-resolve settle: %d → %d", len(resolved), len(more))
            resolved = more
    return resolved


def _declare_outputs(cap: Service, algo: str) -> None:
    """DeclareInterface(transport=ROS2) for every exported contract.
    All algos publish the same contract surface — only the topic differs."""
    bindings = _ALGO_TOPIC_BINDINGS[algo]
    declared = 0
    for contract_id in _EXPORTED_CONTRACTS:
        topic = bindings[contract_id]
        try:
            mapping.declare_ros2_topic(contract_id, topic, qos="reliable")
            declared += 1
            log.info("declared %s → ROS2 topic %s", contract_id, topic)
        except Exception as e:  # noqa: BLE001
            log.warning("declare %s failed: %s", contract_id, e)
    log.info("declared %d/%d output(s) for algo=%s",
             declared, len(_EXPORTED_CONTRACTS), algo)


def _write_resolved_yaml(algo: str, resolved: dict[str, str]) -> str:
    """Write /tmp/<algo>_resolved.yaml with k=v lines. start_engine.sh
    `grep`s these out — yaml-lite is fine, no parser needed."""
    out = os.path.join(RESOLVED_DIR, f"{algo}_resolved.yaml")
    # tf frames default for webots tiago. Real-robot deploys without a
    # base_link TF (no chassis driver, no soma URDF yet) override
    # base_frame to the lidar's own frame (e.g. livox_frame for MID-360)
    # via cfg in the deploy manifest. use_sim_time follows the same
    # cfg path so real-robot bring-ups don't get stuck waiting for a
    # /clock that never comes.
    defaults = {
        "base_frame": "base_link",
        "odom_frame": "odom",
        "map_frame": "map",
        "use_sim_time": "true",
    }
    merged = {**defaults, **resolved}
    with open(out, "w") as f:
        for k, v in merged.items():
            f.write(f"{k}: {v}\n")
    log.info("wrote resolved config → %s (%d keys)", out, len(merged))
    return out


# ── Capability + lifecycle ────────────────────────────────────────────────────
mapping = Service(id=CAP_ID, namespace=NAMESPACE)


@mapping.on_init
def init(cfg: dict):
    """REGISTERED → INITIALIZED. Receives the config dict from
    rbnx via Driver(CMD_INIT, config_json). The mapping cap NEVER reads
    config from disk / env — this gRPC channel is the only sanctioned
    delivery path.

    Order:
      1. Validate algo + sensors block.
      2. Persist algo for start_engine.sh (it greps /tmp/mapping_algo).
      3. Resolve enabled sensor topics from atlas (with retry+settle —
         primitives may still be warming up when CMD_INIT lands).
      4. Write /tmp/<algo>_resolved.yaml for the launch file.
      5. DeclareInterface(ROS2) for every exported map output.
    """
    algo = cfg.get("algo", "rtabmap")
    if algo not in _ALGO_TOPIC_BINDINGS:
        return Err(
            f"unknown algo {algo!r} — supported: {list(_ALGO_TOPIC_BINDINGS)}"
        )
    try:
        _check_binding_complete(algo)
    except RuntimeError as e:
        return Err(str(e))
    if algo == "fastlio2":
        log.warning("algo=fastlio2 is BROKEN (drift); use only for repro/debug")

    log.info("CMD_INIT: algo=%s atlas=%s cap=%s", algo, ATLAS_ENDPOINT, CAP_ID)

    # Persist algo for start_engine.sh.
    os.environ["MAPPING_ALGO"] = algo
    Path("/tmp/mapping_algo").write_text(algo)

    # Discover sensors → resolved.yaml. Raises if `sensors:` block missing.
    try:
        resolved = _retry_resolve(mapping, cfg)
    except RuntimeError as e:
        return Err(str(e))
    # TF / time-source overrides from cfg. Real-robot bring-ups without
    # a chassis driver pass base_frame=livox_frame so rtabmap doesn't
    # block waiting for base_link. use_sim_time=false on real hardware.
    for key in ("base_frame", "odom_frame", "map_frame", "use_sim_time"):
        if key in cfg:
            resolved[key] = str(cfg[key]).lower() if key == "use_sim_time" else str(cfg[key])

    # Map persistence (map_id / mapping vs localization). Adds map_mode +
    # database_path + reset_map to resolved.yaml; start_engine.sh / the
    # launch read them. Empty when no map_id (ephemeral — legacy behaviour).
    try:
        persist = _resolve_persistence(cfg)
    except RuntimeError as e:
        return Err(str(e))
    resolved.update(persist)
    if algo == "rtabmap":
        try:
            overrides_path = _write_rtabmap_overrides(cfg)
        except RuntimeError as e:
            return Err(str(e))
        if overrides_path:
            resolved["rtabmap_overrides_file"] = overrides_path
    # Remember the active map_id so on_shutdown (and the save_map helper)
    # know where to dump the human-previewable map. Only rtabmap persists
    # today; other algos ignore this.
    active_mode = persist.get("map_mode") or str(cfg.get("map_mode", "mapping"))
    active_db = persist.get("database_path", "") if persist else ""
    _ACTIVE.update({
        "algo": algo,
        "map_id": persist.get("map_id", ""),
        "map_dir": os.path.dirname(active_db) if active_db else "",
        "active_db": active_db,
        "map_mode": active_mode,
        "finalized": "false",
    })

    _write_resolved_yaml(algo, resolved)

    # Declare outputs (after resolved.yaml so launch can start in parallel).
    _declare_outputs(mapping, algo)

    # Map web UI (live preview + save/load/pose buttons). On by default at
    # port 8091; override via config `webui_port` (set 0 / "" to disable).
    # Set the env here rather than relying on an external export that gets
    # lost across reboots, so the UI comes up on every boot. Started here so
    # the SLAM topics it previews exist when an operator opens the page.
    # Seed the runtime mode tracker (get_mode) with the startup map_mode.
    map_ops.set_current_mode(active_mode)
    _webui_port = str(cfg.get("webui_port", 8091)).strip()
    if _webui_port and _webui_port != "0":
        os.environ["MAPPING_WEBUI_PORT"] = _webui_port
    webui.set_active_db_hint(_active_db)
    webui.maybe_start()
    return Ok()


# Active-session scratch — set by init, read by on_shutdown / save helpers.
_ACTIVE: dict[str, str] = {}


@mapping.on_shutdown
def shutdown():
    """Best-effort: when a named map (map_id) was being built, dump a
    human-previewable snapshot (occupancy .pgm/.yaml/.png + cloud .pcd +
    meta) next to the rtabmap db before the SLAM nodes are torn down, so
    the map is usable offline without rtabmap's database viewer. The db
    itself is already persistent (rtabmap writes it live at database_path);
    this only adds the portable artifacts. Never fail shutdown on a save
    error — the db is the source of truth."""
    map_dir = _ACTIVE.get("map_dir")
    map_id = _ACTIVE.get("map_id")
    active_db = _active_db()
    expected_db = os.path.join(map_dir or "", "rtabmap.db") if map_dir else ""
    if not map_dir or not map_id or _ACTIVE.get("algo") != "rtabmap":
        return Ok()
    if _ACTIVE.get("map_mode") != "mapping":
        log.info("skip map snapshot on shutdown: mode=%s", _ACTIVE.get("map_mode"))
        return Ok()
    if _ACTIVE.get("finalized") == "true":
        log.info("skip map snapshot on shutdown: map %s already finalized", map_id)
        return Ok()
    if os.path.abspath(active_db or "") != os.path.abspath(expected_db):
        log.info("skip map snapshot on shutdown: active_db=%s is not saved map db=%s", active_db, expected_db)
        return Ok()
    try:
        _export_map_snapshot(map_dir)
    except Exception as e:  # noqa: BLE001
        log.warning("map snapshot export failed (db still saved): %s", e)
    return Ok()


def _export_map_snapshot(map_dir: str) -> None:
    """Run scripts/save_map.py to snapshot the live occupancy grid + cloud
    into map_dir (pgm/yaml/png/pcd/meta). Bounded so a stuck topic can't
    hang shutdown."""
    import subprocess
    script = os.path.join(PKG_HOST_DIR, "scripts", "save_map.py")
    if not os.path.isfile(script):
        log.warning("save_map.py not found at %s — skipping snapshot", script)
        return
    log.info("exporting map snapshot → %s", map_dir)
    subprocess.run(
        ["python3", script, "--out-dir", map_dir, "--timeout", "10"],
        check=False, timeout=30,
    )


# ── Map-management ops: save_map / load_map / pose_estimate ────────────────────

def _save_map_contract_response(out: dict) -> dict:
    return {
        "ok": bool(out.get("ok")),
        "map_id": str(out.get("map_id") or ""),
        "detail": str(out.get("detail") or ""),
    }

def _load_map_contract_response(out: dict) -> dict:
    return {
        "ok": bool(out.get("ok")),
        "detail": str(out.get("detail") or ""),
    }

_PUBLIC_MAP_LIST_KEYS = (
    "map_id",
    "has_spatial_artifact",
    "spatial_ok",
    "artifact_detail",
    "artifact_size",
    "has_preview",
    "updated",
    "meta",
)


def _list_maps_contract_response(out: dict) -> dict:
    if not out.get("ok"):
        return {
            "ok": False,
            "detail": str(out.get("detail") or ""),
            "maps_json": "[]",
        }
    try:
        rows = json.loads(str(out.get("maps_json") or "[]"))
        if not isinstance(rows, list):
            raise ValueError("maps_json is not a list")
        filtered = []
        for row in rows:
            if isinstance(row, dict):
                filtered.append({k: row[k] for k in _PUBLIC_MAP_LIST_KEYS if k in row})
        return {
            "ok": True,
            "detail": str(out.get("detail") or ""),
            "maps_json": json.dumps(filtered, ensure_ascii=False),
        }
    except Exception as exc:
        return {
            "ok": False,
            "detail": f"invalid maps_json from provider: {exc}",
            "maps_json": "[]",
        }

# Exposed as BOTH gRPC (servicer) and MCP (decorated handler), mirroring nav2.
# Shared impls live in map_ops; these are thin adapters. save_map reads the
# active session's live db from _ACTIVE so an ephemeral run can still be
# snapshotted under a name.

def _active_db() -> str:
    active = _ACTIVE.get("active_db") or ""
    if active:
        return active
    md = _ACTIVE.get("map_dir") or ""
    return os.path.join(md, "rtabmap.db") if md else ""


def _saved_map_dir(map_id: str) -> str:
    return os.path.join(MAPS_DIR, _sanitize_map_id(map_id))


def _record_save_result(map_id: str, out: dict) -> None:
    if not out.get("ok"):
        return
    saved_db = os.path.abspath(str(out.get("artifact_path") or ""))
    current_db = os.path.abspath(_active_db() or "")
    if saved_db and current_db and saved_db == current_db:
        _ACTIVE.update({
            "map_id": _sanitize_map_id(map_id),
            "map_dir": os.path.dirname(saved_db),
            "active_db": saved_db,
            "map_mode": "mapping",
            "finalized": "true",
        })


def _record_load_result(map_id: str, out: dict) -> None:
    if not out.get("ok"):
        return
    runtime_db = str(out.get("runtime_db_path") or "")
    _ACTIVE.update({
        "map_id": _sanitize_map_id(map_id),
        "map_dir": _saved_map_dir(map_id),
        "active_db": runtime_db,
        "map_mode": "localization",
        "finalized": "true",
    })


class _SaveMapServicer(contracts_grpc.RobonixServiceMapSaveMapServicer):
    def SaveMap(self, request, context):
        out = map_ops.save_map_impl(request.map_id, request.note, active_db=_active_db())
        _record_save_result(request.map_id, out)
        return map_pb2.SaveMap_Response(**_save_map_contract_response(out))


class _ListMapsServicer(contracts_grpc.RobonixServiceMapListMapsServicer):
    def ListMaps(self, request, context):
        return map_pb2.ListMaps_Response(**_list_maps_contract_response(map_ops.list_maps_impl()))

class _LoadMapServicer(contracts_grpc.RobonixServiceMapLoadMapServicer):
    def LoadMap(self, request, context):
        out = map_ops.load_map_impl(request.map_id, request.mode,
                                    request.has_initial_pose,
                                    request.x, request.y, request.theta)
        _record_load_result(request.map_id, out)
        return map_pb2.LoadMap_Response(**_load_map_contract_response(out))


class _PoseEstimateServicer(contracts_grpc.RobonixServiceMapPoseEstimateServicer):
    def PoseEstimate(self, request, context):
        out = map_ops.pose_estimate_impl(request.x, request.y, request.theta,
                                         request.cov_xy, request.cov_theta)
        return map_pb2.PoseEstimate_Response(**out)


class _SwitchModeServicer(contracts_grpc.RobonixServiceMapSwitchModeServicer):
    def SwitchMode(self, request, context):
        out = map_ops.switch_mode_impl(request.mode)
        if out.get("ok"):
            _ACTIVE["map_mode"] = str(request.mode).strip().lower()
        return map_pb2.SwitchMode_Response(**out)


@mapping.mcp("robonix/service/map/save_map")
def save_map(req: McpSaveMapReq) -> McpSaveMapResp:
    """Snapshot the current SLAM map to disk under a stable map_id so it can be
    reloaded later (load_map) and shared with scene's semantic map. Roam the
    space first to build coverage, then call this to checkpoint it."""
    out = map_ops.save_map_impl(req.map_id, req.note, active_db=_active_db())
    if not out["ok"]:
        raise RuntimeError(out["detail"])
    _record_save_result(req.map_id, out)
    return McpSaveMapResp(**_save_map_contract_response(out))


@mapping.mcp("robonix/service/map/list_maps")
def list_maps(req: McpListMapsReq) -> McpListMapsResp:
    # Public metadata only; provider artifact paths remain private to mapping.
    out = map_ops.list_maps_impl()
    if not out["ok"]:
        raise RuntimeError(out["detail"])
    return McpListMapsResp(**_list_maps_contract_response(out))


@mapping.mcp("robonix/service/map/load_map")
def load_map(req: McpLoadMapReq) -> McpLoadMapResp:
    """Switch SLAM onto a previously-saved map. mode='localization' relocalizes
    against it (stable map frame); mode='mapping' resumes building it. Set
    has_initial_pose + x/y/theta when you roughly know where the robot is, for
    fast convergence."""
    out = map_ops.load_map_impl(req.map_id, req.mode, req.has_initial_pose,
                                req.x, req.y, req.theta)
    if not out["ok"]:
        raise RuntimeError(out["detail"])
    _record_load_result(req.map_id, out)
    return McpLoadMapResp(**_load_map_contract_response(out))


@mapping.mcp("robonix/service/map/pose_estimate")
def pose_estimate(req: McpPoseReq) -> McpPoseResp:
    """Tell SLAM roughly where the robot is (map frame x/y/theta) so its
    localization re-converges — global relocalization or kidnapped-robot
    recovery. rtabmap refines the guess to the true pose via scan matching."""
    out = map_ops.pose_estimate_impl(req.x, req.y, req.theta,
                                     req.cov_xy, req.cov_theta)
    if not out["ok"]:
        raise RuntimeError(out["detail"])
    return McpPoseResp(**out)


@mapping.mcp("robonix/service/map/switch_mode")
def switch_mode(req: McpSwitchReq) -> McpSwitchResp:
    """Flip SLAM between 'mapping' (build/extend the current map) and
    'localization' (relocalize read-only against it) at runtime — no map load,
    no restart. The config's map_mode is only the startup default."""
    out = map_ops.switch_mode_impl(req.mode)
    if not out["ok"]:
        raise RuntimeError(out["detail"])
    _ACTIVE["map_mode"] = str(req.mode).strip().lower()
    return McpSwitchResp(**out)


@mapping.mcp("robonix/service/map/get_mode")
def get_mode(req: McpGetModeReq) -> McpGetModeResp:
    """Read the SLAM mode currently in effect: 'mapping' (building/extending the
    map) or 'localization' (relocalizing read-only). Complements switch_mode —
    use it to report or branch on the real runtime mode rather than guessing."""
    return McpGetModeResp(**map_ops.get_mode_impl())


@mapping.mcp("robonix/service/map/get_pose")
def get_pose(req: McpGetPoseReq) -> McpGetPoseResp:
    """Read the robot's current pose (x, y, theta=yaw) in the SLAM map frame.
    Read-only — use it to record a named waypoint, report where the robot is,
    or decide an action by location. Complements pose_estimate, which SEEDS a
    pose for relocalization rather than reading the current one."""
    return McpGetPoseResp(**map_ops.get_pose_impl())


@mapping.mcp("robonix/service/map/delete_map")
def delete_map(req: McpDeleteReq) -> McpDeleteResp:
    """Permanently delete a saved map by id (its rtabmap.db + preview files on
    disk). Irreversible; does not touch the live running map. Use save_map to
    checkpoint first if unsure."""
    out = map_ops.delete_map_impl(req.map_id)
    if not out["ok"]:
        raise RuntimeError(out["detail"])
    return McpDeleteResp(**out)


@mapping.mcp("robonix/service/map/reset_map")
def reset_map(req: McpResetReq) -> McpResetResp:
    """Clear the LIVE SLAM map and rebuild from the robot's current pose (the
    map-frame origin moves). Does NOT delete saved maps on disk — use this when
    the running map has diverged and you want a clean restart without redeploy."""
    out = map_ops.reset_map_impl()
    if not out["ok"]:
        raise RuntimeError(out["detail"])
    return McpResetResp(**out)


class _GetModeServicer(contracts_grpc.RobonixServiceMapGetModeServicer):
    def GetMode(self, request, context):
        return map_pb2.GetMode_Response(**map_ops.get_mode_impl())


class _GetPoseServicer(contracts_grpc.RobonixServiceMapGetPoseServicer):
    def GetPose(self, request, context):
        return map_pb2.GetPose_Response(**map_ops.get_pose_impl())


class _DeleteMapServicer(contracts_grpc.RobonixServiceMapDeleteMapServicer):
    def DeleteMap(self, request, context):
        return map_pb2.DeleteMap_Response(**map_ops.delete_map_impl(request.map_id))


class _ResetMapServicer(contracts_grpc.RobonixServiceMapResetMapServicer):
    def ResetMap(self, request, context):
        return map_pb2.ResetMap_Response(**map_ops.reset_map_impl())


mapping.attach_grpc_servicer("robonix/service/map/save_map", _SaveMapServicer())
mapping.attach_grpc_servicer("robonix/service/map/list_maps", _ListMapsServicer())
mapping.attach_grpc_servicer("robonix/service/map/load_map", _LoadMapServicer())
mapping.attach_grpc_servicer("robonix/service/map/pose_estimate", _PoseEstimateServicer())
mapping.attach_grpc_servicer("robonix/service/map/switch_mode", _SwitchModeServicer())
mapping.attach_grpc_servicer("robonix/service/map/get_mode", _GetModeServicer())
mapping.attach_grpc_servicer("robonix/service/map/get_pose", _GetPoseServicer())
mapping.attach_grpc_servicer("robonix/service/map/delete_map", _DeleteMapServicer())
mapping.attach_grpc_servicer("robonix/service/map/reset_map", _ResetMapServicer())


def main() -> int:
    mapping.run()
    return 0


if __name__ == "__main__":
    sys.exit(main())
